export enum SelectActionTypeEnum {
  SelectOwnFieldMonster = "selectOwnFieldMonster",
  SelectOwnFieldSpell = "selectOwnFieldSpell",
  SelectOwnFieldCard = "selectOwnFieldCard",
  SelectOwnGraveyardMonster = "selectOwnGraveyardMonster",
  SelectOwnGraveyardSpell = "selectOwnGraveyardSpell",
  SelectOwnGraveyardCard = "selectOwnGraveyardCard",
  SelectOwnHandMonster = "selectOwnHandMonster",
  SelectOwnHandSpell = "selectOwnHandSpell",
  SelectOwnHandCard = "selectOwnHandCard",
  SelectOwnExtraDeckMonster = "selectOwnExtraDeckMonster",
  SelectOwnBanishedMonster = "selectOwnBanishedMonster",
  SelectOwnBanishedSpell = "selectOwnBanishedSpell",
  SelectOwnBanishedCard = "selectOwnBanishedCard",
  SelectOpponentFieldMonster = "selectOpponentFieldMonster",
  SelectOpponentFieldSpell = "selectOpponentFieldSpell",
  SelectOpponentFieldCard = "selectOpponentFieldCard",
  SelectOpponentGraveyardMonster = "selectOpponentGraveyardMonster",
  SelectOpponentGraveyardSpell = "selectOpponentGraveyardSpell",
  SelectOpponentGraveyardCard = "selectOpponentGraveyardCard",
  SelectOpponentHandMonster = "selectOpponentHandMonster",
  SelectOpponentHandSpell = "selectOpponentHandSpell",
  SelectOpponentHandCard = "selectOpponentHandCard",
  SelectOpponentExtraDeckMonster = "selectOpponentExtraDeckMonster",
  SelectOpponentBanishedMonster = "selectOpponentBanishedMonster",
  SelectOpponentBanishedSpell = "selectOpponentBanishedSpell",
  SelectOpponentBanishedCard = "selectOpponentBanishedCard",
}

export type SelectActionType = `${SelectActionTypeEnum}`;
